# NOTE: Best used with the appropriate bamboo terminal emulator theme!!!

ble-face -s argument_error fg=black,bg=red
ble-face -s argument_option fg=#e07870,italic
ble-face -s auto_complete fg=#5a5e5a,italic
ble-face -s cmdinfo_cd_cdpath fg=#88c1e9,bg=black,italic
ble-face -s command_alias fg=blue
ble-face -s command_builtin fg=#ef9946
ble-face -s command_directory fg=#88c1e9
ble-face -s command_file fg=blue
ble-face -s command_function fg=blue
ble-face -s command_keyword fg=purple
ble-face -s disabled fg=#5a5e5a
ble-face -s filename_directory fg=#88c1e9
ble-face -s filename_directory_sticky fg=black,bg=green
ble-face -s filename_executable fg=green,bold
ble-face -s filename_ls_colors none
ble-face -s filename_orphan fg=cyan,bold
ble-face -s filename_other none
ble-face -s filename_setgid fg=black,bg=yellow,underline
ble-face -s filename_setuid fg=black,bg=#ef9946,underline
ble-face -s menu_filter_input fg=black,bg=#dcbf84
ble-face -s overwrite_mode fg=black,bg=cyan
ble-face -s prompt_status_line bg=#5a5e5a
ble-face -s region bg=#383d37
ble-face -s region_insert bg=#383d37
ble-face -s region_match fg=black,bg=#dcbf84
ble-face -s region_target fg=black,bg=purple
ble-face -s syntax_brace fg=#818781
ble-face -s syntax_command fg=blue
ble-face -s syntax_comment fg=#dcbf84
ble-face -s syntax_delimiter fg=#818781
ble-face -s syntax_document fg=cyan,bold
ble-face -s syntax_document_begin fg=cyan,bold
ble-face -s syntax_error fg=black,bg=red
ble-face -s syntax_escape fg=#e07870
ble-face -s syntax_expr fg=#bdb5e3
ble-face -s syntax_function_name fg=blue
ble-face -s syntax_glob fg=#ef9946
ble-face -s syntax_history_expansion fg=blue,italic
ble-face -s syntax_param_expansion fg=red
ble-face -s syntax_quotation fg=green
ble-face -s syntax_tilde fg=#bdb5e3
ble-face -s syntax_varname fg=none
ble-face -s varname_array fg=#ef9946
ble-face -s varname_empty fg=#ef9946
ble-face -s varname_export fg=#ef9946
ble-face -s varname_expr fg=#ef9946
ble-face -s varname_hash fg=#ef9946
ble-face -s varname_number fg=none
ble-face -s varname_readonly fg=#ef9946
ble-face -s varname_transform fg=#ef9946
ble-face -s varname_unset bg=red
ble-face -s vbell_erase bg=#383d37
