# NOTE: Best used with the appropriate bamboo terminal emulator theme!!!

ble-face -s argument_error fg=black,bg=red
ble-face -s argument_option fg=#c05050,italic
ble-face -s auto_complete fg=#a1a7a0,italic
ble-face -s cmdinfo_cd_cdpath fg=#177fff,bg=black,italic
ble-face -s command_alias fg=blue
ble-face -s command_builtin fg=#df5926
ble-face -s command_directory fg=#177fff
ble-face -s command_file fg=blue
ble-face -s command_function fg=blue
ble-face -s command_keyword fg=purple
ble-face -s disabled fg=#a1a7a0
ble-face -s filename_directory fg=#177fff
ble-face -s filename_directory_sticky fg=black,bg=green
ble-face -s filename_executable fg=green,bold
ble-face -s filename_ls_colors none
ble-face -s filename_orphan fg=cyan,bold
ble-face -s filename_other none
ble-face -s filename_setgid fg=black,bg=yellow,underline
ble-face -s filename_setuid fg=black,bg=#df5926,underline
ble-face -s menu_filter_input fg=black,bg=#6f4c05
ble-face -s overwrite_mode fg=black,bg=cyan
ble-face -s prompt_status_line bg=#a1a7a0
ble-face -s region bg=#dadac2
ble-face -s region_insert bg=#dadac2
ble-face -s region_match fg=black,bg=#6f4c05
ble-face -s region_target fg=black,bg=purple
ble-face -s syntax_brace fg=#838781
ble-face -s syntax_command fg=blue
ble-face -s syntax_comment fg=#6f4c05
ble-face -s syntax_delimiter fg=#838781
ble-face -s syntax_document fg=cyan,bold
ble-face -s syntax_document_begin fg=cyan,bold
ble-face -s syntax_error fg=black,bg=red
ble-face -s syntax_escape fg=#c05050
ble-face -s syntax_expr fg=#6c47a0
ble-face -s syntax_function_name fg=blue
ble-face -s syntax_glob fg=#df5926
ble-face -s syntax_history_expansion fg=blue,italic
ble-face -s syntax_param_expansion fg=red
ble-face -s syntax_quotation fg=green
ble-face -s syntax_tilde fg=#6c47a0
ble-face -s syntax_varname fg=none
ble-face -s varname_array fg=#df5926
ble-face -s varname_empty fg=#df5926
ble-face -s varname_export fg=#df5926
ble-face -s varname_expr fg=#df5926
ble-face -s varname_hash fg=#df5926
ble-face -s varname_number fg=none
ble-face -s varname_readonly fg=#df5926
ble-face -s varname_transform fg=#df5926
ble-face -s varname_unset bg=red
ble-face -s vbell_erase bg=#dadac2
